### ISSUE TITLE
Training from scratch for different backbones

### ISSUE THREAD

**Issue by RushiPardeshi** [VQAssessment/DOVER#10]
Hello sir, I am a student, new to VQA, or DL/CV in general, but I was fascinated by your work and wanted to try out different backbones for the technical part of DOVER. To do so, I needed to run the code from scratch, but I noticed no such file was provided. Is high computational resources the reason? If not, could you please provide the file for training from scratch or the reason?

**Comment by teowu** [comment]
Thank you for you interest.

Please refer to our toolbox for technical quality assessment: https://github.com/VQAssessment/FAST-VQA-and-FasterVQA.
We have provided various backbones (ConvNext, Swin, etc), and allow you to set your custom backbones.

**Comment by RushiPardeshi** [comment]
Thanks for the reference. When you mentioned custom backbones, did you mean to take the provided backbones as a basis and then develop my custom backbone?

In my project, I am trying to incorporate multiscale vision transformer(MViT) as the technical backbone(for which I have to compare the codes of SwinT and MViT and learn where to make changes accordingly). Also, since the code for MViT was designed to perform image classification, I am learning how to incorporate it into VQA. I was hoping if you had the training from scratch file, then you could please provide it.

**Comment by teowu** [comment]
All training from scratch were conducted with the https://github.com/VQAssessment/FAST-VQA-and-FasterVQA library.
Please refer to this library.
