### ISSUE TITLE
Running DOVER on a CG animation dataset. How to start?

### ISSUE THREAD

**Issue by egedarici** [VQAssessment/DOVER#11]
Hi, I want to run the application on the dataset Youtube-UGC containing only the animation, gaming, and VR videos in the dataset. 

How should I start and adjust the existing dataset and labels to it?

The only output I want to see is the following:

Compared with all animation videos in the YoutubeUGC_dataset:
-- the technical quality of video [./animation.mp4] is better than 71% of videos, with normalized score 0.65.
-- the aesthetic quality of video [./animation.mp4] is better than 80% of videos, with normalized score 0.86.

Thank you for your response in advance

**Comment by egedarici** [comment]
Another dataset I've found is the CG animation dataset:
https://pan.baidu.com/s/1nOecZS7sYHdX8WclwNH7pQ?pwd=4567
password:4567

What do I need to do to work with this dataset if I wanted to?

**Comment by teowu** [comment]
Thank you for your query.
To achieve this, you have to run the results on all animation videos, and compare them respectively.
You can modify the label list in `examplar_data_labels/YouTubeUGC` to infer on a limited subset of YouTubeUGC.
