### ISSUE TITLE
Couldn't get evaluate_a_set_of_videos.py to work with .avi videos

### ISSUE THREAD

**Issue by egedarici** [VQAssessment/DOVER#12]
Hi,

When I run the model on set of videos it gives this error and finishes. I changed the num_worker to 1 since I had 1  num_worker, but it didn't change anything.

Starting over.
Testing: 0it [00:00, ?it/s]

What could be the reason? Thanks.

**Comment by teowu** [comment]
Please try to use other video loading library (e.g. Moviepy) other than decord (as default used by DOVER).
Decord does not support .AVI format well.
