### ISSUE TITLE
About some implementation details.

### ISSUE THREAD

**Issue by luytvv** [VQAssessment/DOVER#13]
Hello! Thanks for your impressive work! I have some doubt about dover trained on LSVQ. First, could you provide the weight of inflated-ConvNext  Tiny pre-trained with AVA ? Second,  when training dover on LSVQ, has video swin backbone loaded the weight from FastVQA?  Third, when finetuning dover on Konvid, has the author ever encountered a situation where the training suddenly got stuck?

**Comment by teowu** [comment]
Hi, as for the first question, it is easy to train a ConvNext based on AVA. We inflate it after training with image datasets.
As for the second one, yes, only for fine-tuning.
As for the third one, please import torch in the first line of code, can avoid the problem.
