### ISSUE TITLE
Cannot import name 'CLIP3D' from 'open_clip'

### ISSUE THREAD

**Issue by atelili** [VQAssessment/DOVER#17]
Hello, I might find a problem when importing CLIP3D:
ImportError: cannot import name 'CLIP3D' from 'open_clip'.
Thank you

File "/DATA/DOVER/dover/models/conv_backbone.py", line 7, in <module>
    from open_clip import CLIP3D

**Comment by atelili** [comment]
@onurbarut not yet :/

**Comment by ashawn** [comment]
same issue

**Comment by manifest** [comment]
I guess that is a typo. You can simply remove [this line](https://github.com/VQAssessment/DOVER/blob/7857960/dover/models/conv_backbone.py#L7), because the imported identifier is not used anywhere in code.

**Comment by atelili** [comment]
Thanks ^^
