### ISSUE TITLE
hi~how can I get access to DIVIDE-3k datasets? when could you upload the DOVER/DOVER++ training code?thanks~

### ISSUE THREAD

**Issue by LOVEOuziyan** [VQAssessment/DOVER#20]
hi~how can I get access to DIVIDE-3k datasets? when could you upload the DOVER/DOVER++ training code?thanks~

**Comment by leiyaqi** [comment]
> hi~how can I get access to DIVIDE-3k datasets? when could you upload the DOVER/DOVER++ training code?thanks~

hi, have you obtained the dataset yet~

**Comment by LOVEOuziyan** [comment]
no，pity
















At 2023-11-20 09:52:16, "lvjie li" ***@***.***> wrote:

hihow can I get access to DIVIDE-3k datasets? when could you upload the DOVER/DOVER++ training code?thanks

hi, have you obtained the dataset yet~

**Comment by teowu** [comment]
Sorry about the late. See [data release note](https://github.com/VQAssessment/DOVER/tree/master/get_divide_dataset) to obtain the dataset and train it with DOVER++.

**Comment by LOVEOuziyan** [comment]
thank you~
















在 2023-11-21 21:48:22，"Teo (Timothy) Wu Haoning" ***@***.***> 写道：

Closed #20 as completed.
