### ISSUE TITLE
fuse_results explaination

### ISSUE THREAD

**Issue by valeriomieuli** [VQAssessment/DOVER#21]
Hi

I was try to run inference on some videos. I noted that within the `fuse_results` function there are some hardcoded constants that you use to rescale the technical and aesthetic scores. Would you please explain how you defined those numbers?

**Comment by teowu** [comment]
These are statistics (mean, standard dev) from the KoNViD-1k database. You can change them to your custom dataset to get different results. See https://github.com/evalcrafter/EvalCrafter/issues/1 (they use the default mean and standard dev, but could improve with a better one computed from their one datasets) for details.
