### ISSUE TITLE
LSVQ datasets request

### ISSUE THREAD

**Issue by zongh5a** [VQAssessment/DOVER#23]

**Comment by zongh5a** [comment]
Hello. Thanks for your great work. I am trying to retrain the model with LSVQ datasets. However, the form of LSVQ is disabled, and I can not get the datasets. Would you share your LSVQ datasets with me? Thank you very much.

**Comment by teowu** [comment]
Hi please see this in our readme. This is a copy of the dataset we host. 
https://github.com/VQAssessment/DOVER#tip-to-download-lsvq

**Comment by zongh5a** [comment]
Thank you again.
