### ISSUE TITLE
Some error in onnx convert

### ISSUE THREAD

**Issue by wizkdc** [VQAssessment/DOVER#25]
Hi， thank you so much for upload this work. However, I'm having the following problems with onnx converting.

- Error input dimension of views["technical"]. In convert_to_onnx.py, The second dummy input is (4, 3, 32, 224, 224). But when I try to use onnx_inference.py, an error occurs：Got invalid dimensions for input: tech_view for the following indices index: 0 Got: 3 Expected: 4.
- I fixed the above by change the shape of the second dummy input to (3, 3, 32, 224, 224), but I got a result different with the DOVER.pth as below shown.
> python onnx_inference.py -v ./demo/17734.mp4
> 0.333437256801332
> Normalized fused overall score (scale in [0,1]): 0.583

> python evaluate_one_video.py -v ./demo/17734.mp4 -f -d cpu
> 0.7877156560716663
> Normalized fused overall score (scale in [0,1]): 0.6873406273118033.

For question one, I would like to ask if I am doing the modification correctly? If correct, is the difference in the results in question 2 normal? Looking forward to your reply.

**Comment by Littink** [comment]
I have encountered the same problem. Have you resolved it？

**Comment by wizkdc** [comment]
> I have encountered the same problem. Have you resolved it？

I think I found the problem. In DOVER.forward, the input is processed as dict and the first key is "technical”. So the score[0] is the score of technical. But in MinimumDOVER.forward, the first score is "aesthetic_score_pooled". So you can just change the order of  return value of MinimumDOVER.forward.

**Comment by xiefan233** [comment]
> > I have encountered the same problem. Have you resolved it？
> 
> I think I found the problem. In DOVER.forward, the input is processed as dict and the first key is "technical”. So the score[0] is the score of technical. But in MinimumDOVER.forward, the first score is "aesthetic_score_pooled". So you can just change the order of return value of MinimumDOVER.forward.

Hello, I changed the order of the return values from MinimumDOVER as you said. After running convert_to_onnx.py and onnx_inference.py files again, error would still be reported, do you have any solution?

“index: 0 Got: 3 Expected: 4”

**Comment by trekkieSalad** [comment]
> > > I have encountered the same problem. Have you resolved it？
> > 
> > 
> > I think I found the problem. In DOVER.forward, the input is processed as dict and the first key is "technical”. So the score[0] is the score of technical. But in MinimumDOVER.forward, the first score is "aesthetic_score_pooled". So you can just change the order of return value of MinimumDOVER.forward.
> 
> Hello, I changed the order of the return values from MinimumDOVER as you said. After running convert_to_onnx.py and onnx_inference.py files again, error would still be reported, do you have any solution?
> 
> “index: 0 Got: 3 Expected: 4”

To generate a functional onnx model you must do both things in the convert_to_onnx file:
- Reverse the order of aesthetic_score_pooled and technical_score_pooled
- Change torch.randn(4,3,32,224,224) to torch.randn(3,3,32,224,224)

The problem you have is surely caused by the second point.

I hope this helps you to solve it.
