### ISSUE TITLE
Is DOVER suitable for image's quality?

### ISSUE THREAD

**Issue by Jillian2017** [VQAssessment/DOVER#7]
Hi, if I want to evaluate the performance of image, how can I get it?

**Comment by teowu** [comment]
Hi Jillian,

Maybe you can take a try on expanding the images into videos.
However, we will recommend you to follow our project's [IQA-Toolbox](https://github.com/chaofengc/IQA-Pytorch), as there are many open source pre-trained QA models (aesthetic, technical) for images.

**Comment by Jillian2017** [comment]
Thanks a lot
