### ISSUE TITLE
Pure results and Datasets results scales

### ISSUE THREAD

**Issue by mihenriq** [VQAssessment/DOVER#9]
Hello there,
I want to retrieve only the Technical Results calculated from the different datasets, but as you say in ReadMe, some of them may have different scales. I tried to find in the code but it seems I cannot find.
I wanted to convert to my own scale 0 - 5. My question comes up due to some results being smaller than 0 or higher than 1.
Would somebody be able to clarify me this?

Thank you in advance,
Miguel Carvalho

**Comment by teowu** [comment]
The default ```
evaluate_a_set_of_videos.py 
``` has converted the scale to (0,100).
To re-convert it into 1-5, simple linearly rescale them.

To retrieve only technical results, I think the script already provides it.

Best,
Haoning
